"""
Universal conversation state management for SemanticX Framework.
This model tracks conversation context, intent, and workflow state.
"""
from pydantic import BaseModel, Field, ConfigDict
from typing import Any, Dict, List, Optional
import uuid
from datetime import datetime, timezone


def _serialize_tool_call(tool_call):
    """Safely serialize a tool call object."""
    if hasattr(tool_call, 'dict'):
        return tool_call.dict()
    # Fallback for already serialized or simple dicts
    return tool_call


class ConversationState(BaseModel):
    """
    Universal conversation state model for tracking AI conversation context.
    
    This object serves as the "cognitive memory" of the AI, tracking intent,
    entities, conversation history, and the state of any ongoing tool-based operations.
    """
    # Session and Conversation Identifiers
    session_id: str = Field(..., description="Unique identifier for the user session")
    conversation_id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier for the conversation")
    
    # Intent and Context
    intent: Optional[str] = Field(None, description="The primary intent of the user (e.g., 'payment', 'support', 'information')")
    sub_intent: Optional[str] = Field(None, description="The specific sub-intent (e.g., 'transfer', 'create', 'query')")
    domain: Optional[str] = Field(None, description="The domain context (e.g., 'banking', 'healthcare', 'ecommerce')")
    
    # Tool and Function Call State
    last_function_call: Optional[Dict[str, Any]] = Field(None, description="The last function call that was invoked")
    available_tools: List[str] = Field(default_factory=list, description="List of available tool names for this session")
    routing_metadata: Dict[str, Any] = Field(default_factory=dict, description="Routing and orchestration metadata (complexity, model tier, etc.)")
    
    # User Context and Session Data
    user_profile: Dict[str, Any] = Field(default_factory=dict, description="User profile data and context")
    user_id: Optional[str] = Field(None, description="Unique user identifier")
    auth_status: str = Field("unauthenticated", description="Authentication status: unauthenticated, authenticated, failed")
    auth_token: Optional[str] = Field(None, description="Authentication token for the current session")
    auth_method: Optional[str] = Field(None, description="Authentication method in use (pin, voice, biometric)")
    auth_context: Dict[str, Any] = Field(default_factory=dict, description="Metadata for active authentication flow")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional session metadata")
    telemetry_events: List[Dict[str, Any]] = Field(default_factory=list, description="Captured telemetry events for observability")
    
    # Conversational Memory
    conversation_history: List[Dict[str, Any]] = Field(default_factory=list, description="Transcript of the conversation")
    conversation_summary: Optional[str] = Field(None, description="Summarized version of the conversation")
    
    # Orchestration and Planning
    plan: Optional[List[Dict[str, Any]]] = Field(None, description="Multi-step plan generated by the orchestrator")
    current_task: Optional[str] = Field(None, description="Current task being executed")
    current_step: Optional[str] = Field(None, description="Current step in the workflow")
    current_agent: Optional[str] = Field(None, description="Agent responsible for current step")
    plan_context: Dict[str, Any] = Field(default_factory=dict, description="Metadata describing the context in which the plan was generated (intent, sub-intent, timestamp)")
    
    # Flow Management
    is_task_complete: bool = Field(False, description="Flag indicating if current task is complete")
    confirmation_pending: bool = Field(False, description="Flag indicating if waiting for user confirmation")
    auth_pending: bool = Field(False, description="Flag indicating if waiting for user authentication")
    
    # Error and Status Tracking
    error_message: Optional[str] = Field(None, description="Error message to display to user")
    status: str = Field("active", description="Current conversation status")
    retry_count: int = Field(0, description="Number of retry attempts for current operation")
    
    # Timestamps
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="When the conversation was created")
    last_activity: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Last activity timestamp")
    expires_at: Optional[datetime] = Field(None, description="When the conversation expires")
    
    # Vector Memory
    vector_embeddings: List[float] = Field(default_factory=list, description="Vector representation of conversation")
    memory_tags: List[str] = Field(default_factory=list, description="Tags for memory categorization")
    
    def get_serializable_history(self) -> List[Dict[str, Any]]:
        """
        Returns a version of the conversation history that is safe for JSON serialization.
        It specifically handles the conversion of tool call objects.
        """
        serializable_history = []
        for message in self.conversation_history:
            if "tool_calls" in message and message["tool_calls"] is not None:
                # Create a copy to avoid modifying the original state object
                serializable_message = message.copy()
                serializable_message["tool_calls"] = [
                    _serialize_tool_call(tc) for tc in message["tool_calls"]
                ]
                serializable_history.append(serializable_message)
            else:
                serializable_history.append(message)
        return serializable_history
    
    def add_message(self, role: str, content: str, **kwargs):
        """Add a message to the conversation history."""
        message = {
            "role": role,
            "content": content,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            **kwargs
        }
        self.conversation_history.append(message)
        self.last_activity = datetime.now(timezone.utc)
    
    def add_user_message(self, content: str, **kwargs):
        """Add a user message to the conversation."""
        self.add_message("user", content, **kwargs)
    
    def add_assistant_message(self, content: str, **kwargs):
        """Add an assistant message to the conversation."""
        self.add_message("assistant", content, **kwargs)
    
    def add_tool_message(self, tool_call_id: str, name: str, content: str, **kwargs):
        """Add a tool message to the conversation."""
        message = {
            "role": "tool",
            "tool_call_id": tool_call_id,
            "name": name,
            "content": content,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            **kwargs
        }
        self.conversation_history.append(message)
        self.last_activity = datetime.now(timezone.utc)
    
    def get_recent_messages(self, count: int = 10) -> List[Dict[str, Any]]:
        """Get the most recent messages from the conversation."""
        return self.conversation_history[-count:] if self.conversation_history else []
    
    def get_user_messages(self) -> List[str]:
        """Get all user messages from the conversation."""
        return [
            msg["content"] for msg in self.conversation_history 
            if msg.get("role") == "user" and msg.get("content")
        ]
    
    def get_assistant_messages(self) -> List[str]:
        """Get all assistant messages from the conversation."""
        return [
            msg["content"] for msg in self.conversation_history 
            if msg.get("role") == "assistant" and msg.get("content")
        ]
    
    def clear_history(self):
        """Clear the conversation history."""
        self.conversation_history.clear()
        self.conversation_summary = None
    
    def is_expired(self) -> bool:
        """Check if the conversation has expired."""
        if not self.expires_at:
            return False
        return datetime.now(timezone.utc) > self.expires_at
    
    def update_activity(self):
        """Update the last activity timestamp."""
        self.last_activity = datetime.now(timezone.utc)
    
    def set_error(self, error_message: str):
        """Set an error message and update status."""
        self.error_message = error_message
        self.status = "error"
        self.update_activity()
    
    def clear_error(self):
        """Clear the error message and reset status."""
        self.error_message = None
        self.status = "active"
        self.update_activity()

    def clear_plan(self, reason: Optional[str] = None):
        """Clear the current plan and related metadata."""
        self.plan = None
        self.current_step = None
        self.current_task = None
        self.current_agent = None
        self.plan_context = {}
        if reason:
            self.metadata.setdefault("plan_events", []).append({
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "reason": reason
            })
        self.update_activity()

    def get_current_plan_step(self) -> Optional[Dict[str, Any]]:
        """Return the current plan step dictionary, ensuring current_step is aligned."""
        if not self.plan:
            return None

        if not self.current_step and self.plan:
            self.current_step = str(self.plan[0].get("step"))

        for step in self.plan:
            if str(step.get("step")) == str(self.current_step):
                return step
        return None

    def advance_plan(self) -> bool:
        """
        Advance to the next plan step.
        Returns True if moved to a new step, False if plan completed or unavailable.
        """
        if not self.plan:
            return False

        current_step_data = self.get_current_plan_step()
        if not current_step_data:
            return False

        current_index = 0
        for idx, step in enumerate(self.plan):
            if str(step.get("step")) == str(self.current_step):
                current_index = idx
                break

        next_index = current_index + 1
        if next_index < len(self.plan):
            next_step = self.plan[next_index]
            self.current_step = str(next_step.get("step"))
            self.current_task = next_step.get("action")
            self.current_agent = next_step.get("agent")
            self.auth_pending = bool(next_step.get("requires_auth"))
            self.auth_method = next_step.get("auth_method")
            self.is_task_complete = False
            self.metadata.setdefault("plan_events", []).append({
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "reason": "advanced_to_next_step",
                "step": self.current_step,
                "agent": self.current_agent
            })
            self.update_activity()
            return True

        # Completed the plan
        self.clear_plan(reason="plan_completed")
        self.is_task_complete = True
        return False
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert the state to a dictionary for serialization."""
        return {
            "session_id": self.session_id,
            "conversation_id": self.conversation_id,
            "intent": self.intent,
            "sub_intent": self.sub_intent,
            "domain": self.domain,
            "status": self.status,
            "auth_status": self.auth_status,
            "current_step": self.current_step,
            "is_task_complete": self.is_task_complete,
            "error_message": self.error_message,
            "created_at": self.created_at.isoformat(),
            "last_activity": self.last_activity.isoformat(),
            "conversation_summary": self.conversation_summary,
            "memory_tags": self.memory_tags,
        }
    
    model_config = ConfigDict(
        ser_json_timedelta='float'
    )
